### ISSUE TITLE
Project is dead

### ISSUE THREAD

**Issue by oponder** [oponder/big-gollum#29]
@501st-alpha1, I will delete this project ok? 

If you would like to take it anywhere from here, please be my guest!

**Comment by 501st-alpha1** [comment]
Hi!  It has been a while. :grimacing: 

Due to other commitments, I haven't had time to work on this for a while, but I do still have some plans for this (which I will implement Someday :tm:).

In the meantime I'd like to keep the project around, so feel free to transfer ownership to me if you don't want it anymore.

**Comment by oponder** [comment]
Cool :D

I tried to transfer ownership, but you already have a fork. 

Not sure what the best way to proceed is, you could delete the fork and then I _should_ be able to transfer it. Or otherwise you can keep the fork and I'll delete this repo. Let me know what you prefer.

**Comment by 501st-alpha1** [comment]
Okay I fixed that, you can try the transfer again now.

**Comment by oponder** [comment]
I think ya gotta delete the fork entirely:

<img width="523" alt="screen shot 2018-10-16 at 01 23 56" src="https://user-images.githubusercontent.com/455309/46967145-3ed2f880-d0e2-11e8-8836-67c9ee890907.png">

**Comment by 501st-alpha1** [comment]
Done.

**Comment by hoijui** [comment]
can be closed?

**Comment by 501st-alpha1** [comment]
Oops, yep.
